name: dartpkg
description: TODO

# Replace with version: ... to publish on pub.dev.
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  neodart: ^0.1.0
  test: ^1.21.1
